export default {
  gameBaseUrl:'/static/games/',
  posterBaseUrl:'/static/posters/',
  list:[{
    name:'pal',
    title:'仙剑奇侠传一',
    file:'pal.zip',
    command:'PAL!.EXE',
    poster:'pal.webp',
    saveFile:/.rpg$/
  },{
    name:'pal',
    title:'仙剑奇侠传一',
    file:'pal.zip',
    command:'PAL!.EXE',
    poster:'pal.webp',
    saveFile:/.rpg$/
  },{
    name:'pal',
    title:'仙剑奇侠传一',
    file:'pal.zip',
    command:'PAL!.EXE',
    poster:'pal.webp',
    saveFile:/.rpg$/
  },{
    name:'pal',
    title:'仙剑奇侠传一',
    file:'pal.zip',
    command:'PAL!.EXE',
    poster:'pal.webp',
    saveFile:/.rpg$/
  },{
    name:'pal',
    title:'仙剑奇侠传一',
    file:'pal.zip',
    command:'PAL!.EXE',
    poster:'pal.webp',
    saveFile:/.rpg$/
  },{
    name:'pal',
    title:'仙剑奇侠传一',
    file:'pal.zip',
    command:'PAL!.EXE',
    poster:'pal.webp',
    saveFile:/.rpg$/
  },{
    name:'pal',
    title:'仙剑奇侠传一',
    file:'pal.zip',
    command:'PAL!.EXE',
    poster:'pal.webp',
    saveFile:/.rpg$/
  },{
    name:'pal',
    title:'仙剑奇侠传一',
    file:'pal.zip',
    command:'PAL!.EXE',
    poster:'pal.webp',
    saveFile:/.rpg$/
  }]
}
